name: "Send Reviews"
on:
  pull_request:
    types: [opened]
jobs:
  send-reviews:
    runs-on: ubuntu-latest
    steps:
    - name: "Send Review Request to dev team"
      uses: bensiu/review-request-action@v0.1.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: "ccavalloBF"
        team-reviewers: ""
